#ifndef __SETTING_H__
#define __SETTING_H__

#define FAIL -1

#define DEFAULT_DOMAIN_NAME "www.alice.com"
#define DEFAULT_CONNECT_PORT_NUMBER 5555
#define DEFAULT_LISTEN_PORT_NUMBER 8888
#define DEFAULT_LOG_DIRECTORY "logs"
#define DEFAULT_NUM_THREADS 1
#define DEFAULT_SHARED_SECRET "0123456789ABCDEF"

#endif /* __SETTING_H__ */
